version: 0.2
phases:
  install:
    commands:
      - npm install 
      - aws cloudformation package --template-file newapi.json  --s3-bucket cicdapi
                                   --output-template-file master.json
artifacts:
  type: zip
  files:
    - newapi.json
    - master.json
    - index.js
